data:
    dataset: Brain2D
    data_path: /home/dp4018/data/ultrasound-data/Ultrasound-MRI-sagittal/
    mode: mri
    maxsamples: 10
    image_size: 128
    scale: [-1, 1]
    clip_outliers: outer
    to_tensor: false
    normalise: false
    channels: 1

logging:
    tool: tensorboard
    port: 8008

autoencoder:
    model:
        in_channels: 1
        out_channels: 1
        ch: 128
        z_channels : 2
        emb_channels : 1
        ch_mult: [1, 2, 4]
        num_res_blocks: 2
        attn_resolutions: [4]
        dropout: 0.0

    params:
        kl_weight: 0.00001

    training:
        batch_size: 4
        n_epochs: 1
        ckpt_freq: 1
        save_recon_freq: 1
        ckpt_last_only: false
        num_workers: 32 

    validation:
        split: 0.1
        batch_size: 1
        freq: 1
        save_recon_freq: 1
        num_workers: 32
    
    sampling:
        sampling_only: false
        batch_size: 4
        freq: 1000

    optim:
        weight_decay: 0.000
        optimiser: "Adam"
        lr: 0.001
        beta1: 0.9
        amsgrad: false
        eps: 0.00000001
        grad_clip: 1.0

        lr_scheduler:
            scheduler: CosineAnnealingLR
            eta_min: 0.00001
            T_max: 64000

diffusion:
    model:
        type: "simple"
        in_channels: 1
        out_ch: 1
        ch: 128
        ch_mult: [1, 1, 2, 2]
        num_res_blocks: 1
        attn_resolutions: [4, ]
        dropout: 0.0
        ema_rate: 0.999
        resamp_with_conv: True

    params:
        beta_schedule: linear
        beta_start: 0.0001
        beta_end: 0.02
        num_diffusion_timesteps: 1000
        diffusion_sampler : ddim

    training:
        batch_size: 32
        n_epochs: 10000 
        save_recon_freq: 500
        ckpt_freq: 500
        ckpt_last_only: true
        num_workers: 32 

    validation:
        split: null
        batch_size: 32
        freq: 0
        save_recon_freq: 500
        num_workers: 32

    sampling:
        sampling_only: false
        batch_size: 4
        freq: 500
        num_diffusion_timesteps: 1000
        output: last_only

    optim:
        weight_decay: 0.000
        optimizer: "Adam"
        lr: 0.00002
        beta1: 0.9
        amsgrad: false
        eps: 0.00000001
        grad_clip: 1.0

seismic:
    data_file: null
    mode: pids
    save_condition: True

    params:
        frequency: 50