data:
  dataset: Brain2DSampling
  sampling:
    in_size: [256, 256]
    in_channels: 1
  condition:
    mode: stack-trace-pca-100x100
    path: "/home/dp4018/data/ultrasound-data/Ultrasound-Vp-sagittal-data/acoustic/data/stack_pca/for_sampling"
    resize: null
    scale: [0., 1.]
    antialias: true
    clip_outliers: null
    to_tensor: false
    normalise: false

logging:
  tool: JSON

autoencoder:
  model:
    in_channels: 1
    out_channels: 1
    feature_channels: 64
    z_channels: 3
    embbeded_channels: 1
    channels_mult: [1, 2, 2]
    num_res_blocks: 2
    checkpoint: /home/dp4018/scripts/InverseLDM/exps/autoencoders256/cond_vae_trace_pca100/logs/autoencoder/checkpoints/autoencoder_ckpt_latest.pth
    condition:
      in_channels: 1
      feature_channels: 32

  sampling:
    batch_size: 32
    n_samples: 64

diffusion:
  model:
    feature_channels: 128
    channels_mult: [1, 2, 3]
    num_res_blocks: 2
    attention: [0, 1, 2]
    num_transformer_layers: 2
    num_attn_heads: 4
    condition:
      in_channels: 1
      feature_channels: 64

  params:
    beta_start: 0.0015
    beta_end: 0.0205
    num_diffusion_timesteps: 1000
    latent_scaling_factor: 1.
    sampler: ddim

  sampling:
    batch_size: 8
    output: last_only
    n_samples: 64
    skip_steps: 0
    temperature: 1.
