data:
  dataset_path: null
  resize: null
  antialias: true
  scale: null
  clip_outliers: false
  to_tensor: false
  normalise: null

  sampling:
    in_size: [64, 64]
    in_channels: 3

  condition:
    mode: null
    resize: null
    antialias: false
    scale: null
    clip_outliers: false
    to_tensor: false
    normalise: false

logging:
  tool: tensorboard