data:
    image_size: null
    channels: 1
    scale: [0, 1]
    clip_outliers: false
    to_tensor: true
    normalise: [[0.5], [0.5]]

logging:
    tracking_tool: tensorboard

autoencoder:
    model:
        in_channels: 3
        out_channels: 3
        ch: 64
        z_channels : 4
        emb_channels : 4
        ch_mult: [1, 2, 4]
        num_res_blocks: 2
        attn_resolutions: [16]
        dropout: 0.0
        recon_loss: l2
        div_loss: kl
        perceptual_loss: null

    params:
        div_weight: 0.001
        perceptual_weight: 1.
        recon_weight: 1.
        
    training:
        batch_size: 32
        n_epochs: 100 
        save_recon_freq: 100 
        ckpt_freq: 100
        ckpt_last_only: true
        num_workers: 32

    validation:
        split: 0.1
        batch_size: 32
        freq: 10
        save_recon_freq: 100
        num_workers: 32

    sampling:
        sampling_only: false
        batch_size: 32
        freq: 100

    optim:
        weight_decay: 0.000
        optimiser: "Adam"
        lr: 0.00002
        beta1: 0.9
        amsgrad: false
        eps: 0.00000001
        grad_clip: null
        
        lr_scheduler:
            scheduler: null

diffusion:
    model:
        ch: 128
        ch_mult: [1, 1, 2, 2]
        num_res_blocks: 2
        attn_resolutions: [4, ]
        dropout: 0.0
        ema_rate: 0.999
        loss: l2

    params:
        beta_schedule: linear
        beta_start: 0.0001
        beta_end: 0.02
        num_diffusion_timesteps: 100
        latent_scaling_factor: 1.
        sampler : ddpm

    training:
        batch_size: 32
        n_epochs: 100
        save_recon_freq: 0 
        ckpt_freq: 100
        ckpt_last_only: true
        num_workers: 32 

    validation:
        split: 0.1
        batch_size: 32
        freq: 10
        save_recon_freq: 0 
        num_workers: 4

    sampling:
        sampling_only: false
        batch_size: 32
        freq: 100
        output: last_only

    optim:
        weight_decay: 0.000
        optimiser: "Adam"
        lr: 0.00002
        beta1: 0.9
        amsgrad: false
        eps: 0.00000001
        grad_clip: null

        lr_scheduler:
            scheduler: null

seismic:
    data_file: null
    mode: pids
    save_condition: True
